# Generated by Django 3.2.4 on 2021-06-24 02:18

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileFeedbackEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=50)),
                ('PublicationDate', models.DateField(auto_now_add=True)),
                ('EventDate', models.DateField(default=datetime.date.today)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='FileFeedbackOwner', to=settings.AUTH_USER_MODEL, verbose_name='Владелец события')),
            ],
        ),
        migrations.CreateModel(
            name='FileFeedbackEventToSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedbackFile', models.FileField(blank=True, null=True, upload_to='files/')),
                ('SubscriptionDate', models.DateField(default=datetime.date.today)),
                ('event', models.ManyToManyField(to='feedbackfile_app.FileFeedbackEvent', verbose_name='Событие')),
                ('subscriber', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Подписчик')),
            ],
        ),
    ]
