# Generated by Django 3.2.4 on 2021-06-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbackfile_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filefeedbackeventtosubscriber',
            name='feedback',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
