# Generated by Django 3.2.4 on 2021-06-18 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EventName', models.CharField(max_length=50)),
                ('PublicationDate', models.IntegerField()),
                ('EventDate', models.IntegerField()),
            ],
            bases=(models.Model, datetime.date),
        ),
    ]
