# Generated by Django 3.2.4 on 2021-06-23 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_eventtosubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtosubscriber',
            name='event',
        ),
        migrations.AddField(
            model_name='eventtosubscriber',
            name='event',
            field=models.ManyToManyField(blank=True, null=True, to='app.Event', verbose_name='Событие'),
        ),
        migrations.RemoveField(
            model_name='eventtosubscriber',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='eventtosubscriber',
            name='subscriber',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
    ]
