# Generated by Django 3.2.4 on 2021-06-19 06:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210618_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='EventDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='event',
            name='PublicationDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
