# Generated by Django 3.2.4 on 2021-06-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210623_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtosubscriber',
            name='event',
            field=models.ManyToManyField(to='app.Event', verbose_name='Событие'),
        ),
    ]
