# Generated by Django 3.2.4 on 2021-06-23 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_eventtosubscriber_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtosubscriber',
            name='subscriber',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Подписчик'),
        ),
    ]
