# Generated by Django 3.2.4 on 2021-06-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_eventtosubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtosubscriber',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventtosubscriber',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='eventtosubscriber',
            name='events',
            field=models.ManyToManyField(to='app.Event'),
        ),
    ]
