# Generated by Django 3.2.4 on 2021-06-24 01:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_eventtosubscriber_subscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtosubscriber',
            name='SubscribeDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
