# Generated by Django 3.2.4 on 2021-06-22 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_eventtosubscriber_eventsubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsubscriber',
            name='events',
        ),
        migrations.AddField(
            model_name='eventsubscriber',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.event', verbose_name='Событие'),
        ),
    ]
