# Generated by Django 3.2.4 on 2021-06-24 01:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_rename_subscribedate_eventtosubscriber_subscriptiondate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='SimpleEvent',
        ),
    ]
