# Generated by Django 3.2.4 on 2021-06-22 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210622_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtosubscriber',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.event', verbose_name='Событие'),
        ),
    ]
