# Generated by Django 3.2.4 on 2021-06-24 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210624_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefeedbackeventtosubscriber',
            name='event',
            field=models.ManyToManyField(to='app.FileFeedbackEvent', verbose_name='Событие'),
        ),
    ]
