# Generated by Django 3.2.4 on 2021-06-24 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_filefeedbackeventtosubscriber_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filefeedbackeventtosubscriber',
            name='event',
        ),
        migrations.RemoveField(
            model_name='filefeedbackeventtosubscriber',
            name='subscriber',
        ),
        migrations.DeleteModel(
            name='FileFeedbackEvent',
        ),
        migrations.DeleteModel(
            name='FileFeedbackEventToSubscriber',
        ),
    ]
